CREATE TABLE books(
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    author VARCHAR(80) NOT NULL,
    languages TEXT[] NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
)