ALTER TABLE users
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users 
ALTER COLUMN email SET NOT NULL;

ALTER TABLE users 
ALTER COLUMN name SET NOT NULL;

ALTER TABLE users 
ALTER COLUMN password SET NOT NULL;
